spring.application.name=TandilRec
server.port=8081
management.endpoints.web.cors.allowed-origins=[https://example.com]
management.endpoints.web.cors.allowed-methods=GET,POST,DELETE, PUT
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/TandilRec
spring.datasource.username=admin
spring.datasource.password=zoe81204
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update