spring.application.name=TandilRec
server.port=8081
management.endpoints.web.cors.allowed-origins=${FRONTEND_URL}
management.endpoints.web.cors.allowed-methods=${CORS_ALLOWED}
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url={DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update